---

- name: Opensips | Add key server
  become: true
  shell: "curl https://apt.opensips.org/pubkey.gpg | apt-key add -"

- name: Opensips | Add opensips reposity
  become: true
  shell: echo "deb https://apt.opensips.org bullseye 3.2-releases" >/etc/apt/sources.list.d/opensips.list

- name: Opensips | Add opensips-cli reposity
  become: true
  shell: echo "deb https://apt.opensips.org bullseye cli-nightly" >/etc/apt/sources.list.d/opensips-cli.list

- name: Opensips | Update APT Cache.
  become: true
  apt: update_cache=yes
  when: opensips_manage_repo

- name: Opensips | Installation.
  become: true
  apt:
    name: "{{ opensips_debian_packages }}"
    state: present
  notify: Restart opensips

- name: Opensips | Configure.
  become: true
  template:
    src: "{{ opensips_config_template_dir }}/{{ item }}.j2"
    dest: "{{ opensips_conf_dir }}/{{ item }}"
    backup: true
  with_items: "{{ opensips_conf_files }}"
  notify: Restart opensips
  when: opensips_install_conf
      
- name: Opensips | Create database.
  expect:
    command: opensips-cli -f /etc/opensips/opensips-cli.conf -x database create
    responses:
      Password: "{{ opensips_db_root_pass }}"
  run_once: true
  notify: Restart opensips

- name: Opensips | put script  to tmp.
  become: true
  template:
    src: "{{ opensips_db_script_dir }}/{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items: "{{ opensips_db_script_file }}"

- name: Opensips | add column.
  become: true
  shell: psql -h {{ opensips_bind_host }} -U {{ opensips_db_root_user }} -d {{ opensips_db_name }} -a -f {{ opensips_db_script_file }} chdir=/tmp
